## Artificial Neural Networks 
### Case on : Churn Modeling ---> predict which customers churn or not

In [1]:
# =============================================================================
# Importing the libraries
# =============================================================================
 
import numpy as np # Data Handling
import matplotlib.pyplot as plt # Data Visualization
import pandas as pd # # Data Handling
import os # Working Directory
from sklearn.preprocessing import LabelEncoder, OneHotEncoder # Transformation of Categorical columns into Numerical Values
from sklearn.compose import ColumnTransformer # Transformation
from sklearn.model_selection import train_test_split # Splitting Data into Train & Test
from sklearn.preprocessing import StandardScaler # Neural Networks --> generally standarize the data
from sklearn.metrics import confusion_matrix # Model Evaluation 
from sklearn.metrics import classification_report # Model Evaluation 
import keras # Deep Learning Framework 
from keras.models import Sequential # Adding layers in the Neural Network 
from keras.layers import Dense # Adding layers in the Neural Network 

### 1. Reading the data

In [2]:
# =============================================================================
# Importing the dataset
# =============================================================================
os.chdir(R'C:\Users\arpend.ganguly\OneDrive - Accenture\2021_DELL_ALL_Backup\02_G_IVY\Python\06NEURAL_NETWORKS')
os.getcwd()
dataset = pd.read_csv('Churn_Modelling.csv')
print("The shape of data is", dataset.shape)
dataset.head()

The shape of data is (10000, 14)


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
dataset.Geography.value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [6]:
dataset.Gender.value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

### 2. Data Processing
--- i) Creating the **Final Feature Set and Dependent**

--- ii) Converting the **Categorical columns into Numerical ones**

--- iii) Applying the **Train Test Split**

--- iv) Applying the **Standarization across the dataframe**



In [15]:
# =============================================================================
# Data Pre-Processing
# =============================================================================

#1. Creating the Dependent and Independent Features
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("Feature Set:")
print(X.shape)
print(X)
print("Dependent Set:")
print(y)

Feature Set:
(10000, 10)
[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
Dependent Set:
[1 0 1 ... 1 1 0]


In [16]:
# Encoding categorical data through label encoding 
labelencoder_X_1 = LabelEncoder() # Geography Column 
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder() # Gender Column 
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
print("Feature Set post label encoding--->")
print(X.shape)
print(X)

Feature Set post label encoding--->
(10000, 10)
[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [17]:
#onehotencoder = OneHotEncoder(categorical_features = [1])
ct = ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)
X = X[:, 1:]
print(X.shape)
print(X)

(10000, 11)
[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


In [20]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling for faster computation
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print("Standarized X Train --->")
print(X_train)
print("Standarized X Test --->")
print(X_test)
print("Data Transformations for Neural Networks is complete! ")

Standarized X Train --->
[[-0.5698444   1.74309049  0.16958176 ...  0.64259497 -1.03227043
   1.10643166]
 [ 1.75486502 -0.57369368 -2.30455945 ...  0.64259497  0.9687384
  -0.74866447]
 [-0.5698444  -0.57369368 -1.19119591 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [-0.5698444  -0.57369368  0.9015152  ...  0.64259497 -1.03227043
   1.41231994]
 [-0.5698444   1.74309049 -0.62420521 ...  0.64259497  0.9687384
   0.84432121]
 [ 1.75486502 -0.57369368 -0.28401079 ...  0.64259497 -1.03227043
   0.32472465]]
Standarized X Test --->
[[ 1.75486502 -0.57369368 -0.55204276 ...  0.64259497  0.9687384
   1.61085707]
 [-0.5698444  -0.57369368 -1.31490297 ...  0.64259497 -1.03227043
   0.49587037]
 [-0.5698444   1.74309049  0.57162971 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-0.5698444   1.74309049 -0.74791227 ...  0.64259497 -1.03227043
   0.71888467]
 [ 1.75486502 -0.57369368 -0.00566991 ...  0.64259497  0.9687384
  -1.54507805]
 [ 1.75486502 -0.57369368 -0.79945688 ...  0.64259497 

### 3. Creating the Neural Network Architecture

In [ ]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(6, kernel_initializer= 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(6, kernel_initializer=  'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(1, kernel_initializer='uniform', activation = 'sigmoid'))

#---------------------------------------------------------------------->
#Output_dim = nodes of first hidden layer
#init = initialization of the weights based on an uniform distribution
#activation = activation function
#input_dim = no. of input features
#---------------------------------------------------------------------->

#### 4. Compiling the Architecture

In [24]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#Binary Cross entropy since we are focussing on Output class [0,1]
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 3s 3ms/step - loss: 0.5060 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 2s 3ms/step - loss: 0.5059 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 2s 3ms/step - loss: 0.5060 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 2s 2ms/step - loss: 0.5059 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 2s 2ms/step - loss: 0.5059 - accuracy: 0.7960
Epoch 6/100
800/800 [==============================] - 2s 3ms/step - loss: 0.5060 - accuracy: 0.7960
Epoch 7/100
800/800 [==============================] - 2s 3ms/step - loss: 0.5060 - accuracy: 0.7960
Epoch 8/100
800/800 [==============================] - 2s 3ms/step - loss: 0.5060 - accuracy: 0.7960
Epoch 9/100
800/800 [==============================] - 2s 2ms/step - loss: 0.5060 - accuracy: 0.7960
Epoch 10/100
800/800 [==============================] - 2s 2ms/step - loss: 0.5059 - accura

#### 5. Making the Final Predictions

In [28]:
# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)#Converting 1, 0 Class

# # Making the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(classification_report(y_pred, 
            y_test))

63/63 [==============================] - 0s 3ms/step
              precision    recall  f1-score   support

           0       1.00      0.80      0.89      2000
           1       0.00      0.00      0.00         0

    accuracy                           0.80      2000
   macro avg       0.50      0.40      0.44      2000
weighted avg       1.00      0.80      0.89      2000



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
y_test_df=pd.DataFrame({'y_test_value':y_test})

In [33]:
y_test_df.y_test_value.value_counts()

0    1595
1     405
Name: y_test_value, dtype: int64

In [34]:
1595/(1595+405)

0.7975